### ISSUE TITLE
Research ATM Systems and Security Vulnerabilities

### ISSUE THREAD

**Issue by adarshkrsingh07** [adarshkrsingh07/22BCD-1#29]
- Conduct thorough research on ATM systems, including their hardware components, software architecture, communication protocols, and security mechanisms.

- Study common vulnerabilities and attack vectors that ATM machines are susceptible to, such as skimming, card trapping, malware attacks, physical tampering, etc.

**Comment by ayush2442** [comment]
Common ATM Vulnerabilities and Attack Vectors includes:

1. Skimming:
-> Criminals attach devices (skimmers) to the card reader to steal card data.
-> Skimmers can be physical overlays or hidden cameras capturing PINs.

2. Card Trapping:
-> Fraudsters place physical traps inside the card slot to retain cards.
-> Victims leave without their cards, allowing attackers to retrieve them later.

3. Malware Attacks:
-> Malicious software (e.g., Skimer, GreenDispenser) infects ATMs.
-> Malware can manipulate transactions, steal funds, or collect card data.

4. Physical Tampering:
-> Attackers physically manipulate ATMs to access cash.
-> Techniques include drilling, cutting, or prying open ATM components.

5. Black Box Attacks:
-> Criminals connect a “Black Box” device to the ATM to send unauthorized commands to the cash dispenser.
-> Cash is collected by the attackers.
